---
- hosts: all
  become: true

  vars:
    motd:
      - Ansible Managed Node by jello
    new_user: NewUserTest

  tasks:

  - name: Install python3 and pip3
    package:
      name:
        - python3
        - python3-pip
      state: latest
      update_cache: yes

  - name: use pip3 as default pip
    lineinfile:
      path: /etc/alternatives/pip
      line: /user/bin/pip3
      create: yes

  - name: use python3 as default python
    lineinfile:
      path: /etc/alternatives/python
      line: /user/bin/python3
      create: yes

  - name: Install Java open-jdk
    apt:
      name: openjdk-17-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install Java open-jdk
    dnf:
      name: java-11-openjdk
      state: latest
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: Create MOTD  
    ansible.builtin.debug:
      msg:
        - "{{ motd }}"

  - name: Create user with variable
    user:
      name: "{{ new_user }}"
      state: present
